In [11]:
# Menginstal library Sastrawi untuk proses stopword removal dan stemming pada teks Bahasa Indonesia
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.13/dist-packages (1.0.1)

In [12]:
# Mengimpor library yang digunakan dalam proses preprocessing
import re
import pandas as pd

# Mengimpor modul Sastrawi untuk menghapus stopword dan mengubah kata berimbuhan menjadi kata dasar
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [15]:
# Membuat 5 dokumen bertema penggunaan teknologi dalam pembelajaran mahasiswa
dokumen = [
    "Teknologi sangat membantu mahasiswa dalam proses belajar. Mahasiswa bisa menggunakan laptop untuk mengerjakan tugas kuliah.",
    "Mahasiswa sering menggunakan internet untuk mencari materi perkuliahan. Dengan internet, mencari informasi menjadi lebih mudah dan cepat.",
    "Laptop banyak digunakan mahasiswa untuk membuat tugas kuliah. Selain untuk tugas, laptop juga bisa digunakan untuk mengikuti kelas online.",
    "Aplikasi pembelajaran membantu mahasiswa memahami materi kuliah. Mahasiswa bisa membaca materi dan mengerjakan tugas melalui aplikasi tersebut.",
    "Pembelajaran menggunakan teknologi membuat kegiatan kuliah menjadi lebih praktis. Mahasiswa dapat belajar dari rumah dengan bantuan internet dan perangkat komputer."
]

# Menampilkan jumlah dokumen yang digunakan
print("Jumlah dokumen:", len(dokumen))

Jumlah dokumen: 5

In [16]:
# Membuat stopword remover Bahasa Indonesia menggunakan Sastrawi
stopword_factory = StopWordRemoverFactory()
stopword_remover = stopword_factory.create_stop_word_remover()

# Membuat stemmer Bahasa Indonesia menggunakan Sastrawi
stemmer_factory = StemmerFactory()
stemmer = stemmer_factory.create_stemmer()

In [17]:
def preprocess_text(text):
    """
    Melakukan preprocessing teks dengan tahapan:
    1. Case folding
    2. Cleaning
    3. Tokenisasi
    4. Stopword removal
    5. Stemming
    """

    # Case folding: mengubah seluruh huruf menjadi huruf kecil
    text = text.lower()

    # Cleaning: menghapus angka, tanda baca,
    # dan karakter khusus
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Menghapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    # Tokenisasi: memisahkan teks menjadi beberapa token/kata
    tokens = text.split()

    # Menghapus stopword dari teks
    text_no_stopword = stopword_remover.remove(' '.join(tokens))
    tokens_no_stopword = text_no_stopword.split()

    # Stemming: mengubah kata berimbuhan menjadi kata dasar
    tokens_stemmed = [
        stemmer.stem(token)
        for token in tokens_no_stopword
    ]

    return tokens_stemmed

In [18]:
# Menerapkan fungsi preprocessing pada seluruh dokumen
hasil_preprocessing = []

for teks in dokumen:
    hasil = preprocess_text(teks)
    hasil_preprocessing.append(hasil)

# Menampilkan hasil preprocessing setiap dokumen
for i, hasil in enumerate(hasil_preprocessing, start=1):
    print(f"Dokumen {i}:")
    print(hasil)
    print()

Dokumen 1:
['teknologi', 'sangat', 'bantu', 'mahasiswa', 'proses', 'ajar', 'mahasiswa', 'guna', 'laptop', 'kerja', 'tugas', 'kuliah']

Dokumen 2:
['mahasiswa', 'sering', 'guna', 'internet', 'cari', 'materi', 'kuliah', 'internet', 'cari', 'informasi', 'jadi', 'lebih', 'mudah', 'cepat']

Dokumen 3:
['laptop', 'banyak', 'guna', 'mahasiswa', 'buat', 'tugas', 'kuliah', 'tugas', 'laptop', 'bisa', 'guna', 'untuk', 'ikut', 'kelas', 'online']

Dokumen 4:
['aplikasi', 'ajar', 'bantu', 'mahasiswa', 'paham', 'materi', 'kuliah', 'mahasiswa', 'baca', 'materi', 'kerja', 'tugas', 'lalu', 'aplikasi', 'sebut']

Dokumen 5:
['ajar', 'guna', 'teknologi', 'buat', 'giat', 'kuliah', 'jadi', 'lebih', 'praktis', 'mahasiswa', 'ajar', 'rumah', 'bantu', 'internet', 'perangkat', 'komputer']

In [19]:
# Menampilkan perbandingan teks sebelum dan sesudah preprocessing
for i in range(len(dokumen)):
    print(f"===== Dokumen {i + 1} =====")

    # Teks asli sebelum preprocessing
    print("Sebelum:")
    print(dokumen[i])

    # Hasil setelah preprocessing
    print("\nSesudah:")
    print(" ".join(hasil_preprocessing[i]))

    print("\n")

===== Dokumen 1 =====
Sebelum:
Teknologi sangat membantu mahasiswa dalam proses belajar. Mahasiswa bisa menggunakan laptop untuk mengerjakan tugas kuliah.

Sesudah:
teknologi sangat bantu mahasiswa proses ajar mahasiswa guna laptop kerja tugas kuliah


===== Dokumen 2 =====
Sebelum:
Mahasiswa sering menggunakan internet untuk mencari materi perkuliahan. Dengan internet, mencari informasi menjadi lebih mudah dan cepat.

Sesudah:
mahasiswa sering guna internet cari materi kuliah internet cari informasi jadi lebih mudah cepat


===== Dokumen 3 =====
Sebelum:
Laptop banyak digunakan mahasiswa untuk membuat tugas kuliah. Selain untuk tugas, laptop juga bisa digunakan untuk mengikuti kelas online.

Sesudah:
laptop banyak guna mahasiswa buat tugas kuliah tugas laptop bisa guna untuk ikut kelas online


===== Dokumen 4 =====
Sebelum:
Aplikasi pembelajaran membantu mahasiswa memahami materi kuliah. Mahasiswa bisa membaca materi dan mengerjakan tugas melalui aplikasi tersebut.

Sesudah:
aplikasi ajar bantu mahasiswa paham materi kuliah mahasiswa baca materi kerja tugas lalu aplikasi sebut


===== Dokumen 5 =====
Sebelum:
Pembelajaran menggunakan teknologi membuat kegiatan kuliah menjadi lebih praktis. Mahasiswa dapat belajar dari rumah dengan bantuan internet dan perangkat komputer.

Sesudah:
ajar guna teknologi buat giat kuliah jadi lebih praktis mahasiswa ajar rumah bantu internet perangkat komputer

In [24]:
# Menghitung jumlah token sebelum dan sesudah preprocessing
data_token = []

for i in range(len(dokumen)):
    # Token sebelum preprocessing
    token_sebelum = re.findall(r'\b[a-zA-Z]+\b', dokumen[i].lower())

    # Token setelah preprocessing
    token_sesudah = hasil_preprocessing[i]

    data_token.append({
        "Dokumen": f"D{i + 1}",
        "Token Sebelum": len(token_sebelum),
        "Token Sesudah": len(token_sesudah)
    })

# Membuat tabel hasil perhitungan token
df_token = pd.DataFrame(data_token)

display(df_token)

  Dokumen  Token Sebelum  Token Sesudah
0      D1             15             12
1      D2             17             14
2      D3             19             15
3      D4             17             15
4      D5             20             16

In [25]:
# Menghitung persentase pengurangan jumlah token
df_token["Pengurangan"] = (
    df_token["Token Sebelum"] - df_token["Token Sesudah"]
)

df_token["Persentase Pengurangan"] = (
    df_token["Pengurangan"] /
    df_token["Token Sebelum"] * 100
)

# Menampilkan hasil dengan pembulatan dua angka desimal
display(
    df_token[
        [
            "Dokumen",
            "Token Sebelum",
            "Token Sesudah",
            "Pengurangan",
            "Persentase Pengurangan"
        ]
    ].round(2)
)

  Dokumen  Token Sebelum  Token Sesudah  Pengurangan  Persentase Pengurangan
0      D1             15             12            3                   20.00
1      D2             17             14            3                   17.65
2      D3             19             15            4                   21.05
3      D4             17             15            2                   11.76
4      D5             20             16            4                   20.00

In [26]:
# Menampilkan token sebelum dan sesudah preprocessing
for i in range(len(dokumen)):

    # Mengambil token dari teks asli
    token_sebelum = re.findall(
        r'\b[a-zA-Z]+\b',
        dokumen[i].lower()
    )

    print(f"===== Dokumen {i + 1} =====")

    print("Token sebelum:")
    print(token_sebelum)

    print("\nToken sesudah:")
    print(hasil_preprocessing[i])

    print("\n")

===== Dokumen 1 =====
Token sebelum:
['teknologi', 'sangat', 'membantu', 'mahasiswa', 'dalam', 'proses', 'belajar', 'mahasiswa', 'bisa', 'menggunakan', 'laptop', 'untuk', 'mengerjakan', 'tugas', 'kuliah']

Token sesudah:
['teknologi', 'sangat', 'bantu', 'mahasiswa', 'proses', 'ajar', 'mahasiswa', 'guna', 'laptop', 'kerja', 'tugas', 'kuliah']


===== Dokumen 2 =====
Token sebelum:
['mahasiswa', 'sering', 'menggunakan', 'internet', 'untuk', 'mencari', 'materi', 'perkuliahan', 'dengan', 'internet', 'mencari', 'informasi', 'menjadi', 'lebih', 'mudah', 'dan', 'cepat']

Token sesudah:
['mahasiswa', 'sering', 'guna', 'internet', 'cari', 'materi', 'kuliah', 'internet', 'cari', 'informasi', 'jadi', 'lebih', 'mudah', 'cepat']


===== Dokumen 3 =====
Token sebelum:
['laptop', 'banyak', 'digunakan', 'mahasiswa', 'untuk', 'membuat', 'tugas', 'kuliah', 'selain', 'untuk', 'tugas', 'laptop', 'juga', 'bisa', 'digunakan', 'untuk', 'mengikuti', 'kelas', 'online']

Token sesudah:
['laptop', 'banyak', 'guna', 'mahasiswa', 'buat', 'tugas', 'kuliah', 'tugas', 'laptop', 'bisa', 'guna', 'untuk', 'ikut', 'kelas', 'online']


===== Dokumen 4 =====
Token sebelum:
['aplikasi', 'pembelajaran', 'membantu', 'mahasiswa', 'memahami', 'materi', 'kuliah', 'mahasiswa', 'bisa', 'membaca', 'materi', 'dan', 'mengerjakan', 'tugas', 'melalui', 'aplikasi', 'tersebut']

Token sesudah:
['aplikasi', 'ajar', 'bantu', 'mahasiswa', 'paham', 'materi', 'kuliah', 'mahasiswa', 'baca', 'materi', 'kerja', 'tugas', 'lalu', 'aplikasi', 'sebut']


===== Dokumen 5 =====
Token sebelum:
['pembelajaran', 'menggunakan', 'teknologi', 'membuat', 'kegiatan', 'kuliah', 'menjadi', 'lebih', 'praktis', 'mahasiswa', 'dapat', 'belajar', 'dari', 'rumah', 'dengan', 'bantuan', 'internet', 'dan', 'perangkat', 'komputer']

Token sesudah:
['ajar', 'guna', 'teknologi', 'buat', 'giat', 'kuliah', 'jadi', 'lebih', 'praktis', 'mahasiswa', 'ajar', 'rumah', 'bantu', 'internet', 'perangkat', 'komputer']

### Analisis

Preprocessing yang dilakukan membuat teks menjadi lebih bersih dan sederhana. Beberapa bagian seperti huruf kapital, tanda baca, angka, dan kata yang kurang penting dihilangkan agar tidak terlalu banyak mengganggu proses pengolahan data. Stemming juga membuat kata berimbuhan menjadi kata dasar sehingga kata yang mirip lebih mudah dikenali. Dengan begitu, jumlah token berkurang dan data menjadi lebih mudah digunakan untuk proses pencarian dokumen pada sistem Information Retrieval (IR).